### ISSUE TITLE
z-order sorting for roads fails

### ISSUE THREAD

**Issue by matkoniecz** [tangrams/highways-demo#7]
Expected: bridge will be marked by rendering of road outline of bridge above road below bridge

What happens: roads are rendered like on junction

layers are used correctly in OSM data

https://mapzen.com/tangram/play/?#18.25000/50.08117/19.89062

![selection_005](https://user-images.githubusercontent.com/899988/27252827-016870d6-5368-11e7-9739-348e6e50dfde.png)
![selection_006](https://user-images.githubusercontent.com/899988/27252829-0239ee72-5368-11e7-92f1-a2f0b15b8192.png)

It seems that

```
        z-order:
            filter: { $zoom: {min: 14} }
            draw:
                flatlines:
                    # let roads sort themselves past zoom 14
                    order: function() { return feature.sort_rank; }
                    # but give them all the same outline
                    outline:
                        order: 352 # magic number

            bridges-tunnels:
                filter: { any: [is_bridge: true, is_tunnel: true] }
                draw:
                    flatlines:
                        outline:
                            # except bridges and tunnels, their outlines should also self-sort
                            order: function() { return feature.sort_rank; }
```
was supposed to handle this but it works only sometimes.
